### ISSUE TITLE
ImportError: cannot import name simplejson

### ISSUE THREAD

**Issue by mshaq09** [edavis/django-carson#2]
from django.utils import simplejson as json

from django.utils import simplejson as json
ImportError: cannot import name simplejson

should be change to just json

**Comment by andreashhpetersen** [comment]
I have that problem too, so I'm not able to run migrate..

Changing it to json doesn't seem to help me either, instead I'm just getting:
ImportError: cannot import name json

**Comment by edavis** [comment]
Sorry, I haven't touched this project in years and don't do much in Django anymore.

I'm afraid this is one you'll have to fork and update to get working.

I'll take a look at a PR but otherwise I consider this project archived.
